export const SCORING=['normal','multiple','all_correct','excluded'];
export const questionKey=q=>`${q.section.toUpperCase()}${String(q.number).padStart(2,'0')}`;
export function validatePublicData(exam,questions){const errors=[],ids=new Set(),positions=new Set();if(exam?.schemaVersion!=='1.0')errors.push('schemaVersionが未対応です');if(!exam?.examId)errors.push('examIdがありません');if(!Array.isArray(questions))return[...errors,'問題一覧が不正です'];questions.forEach((q,i)=>{const p=`${q.section}:${q.number}`;if(q.examId!==exam.examId)errors.push(`問${i+1}: examId不一致`);if(!q.id||ids.has(q.id))errors.push(`問${i+1}: ID重複`);if(positions.has(p))errors.push(`問${i+1}: 区分・番号重複`);if(!exam.categories.includes(q.category))errors.push(`問${i+1}: 未定義分野`);if(!Number.isInteger(q.choiceCount)||q.choiceCount<2)errors.push(`問${i+1}: 選択肢数不正`);if(!(Number(q.points)>0))errors.push(`問${i+1}: 配点不正`);if('correctAnswers'in q||'scoring'in q||'explanation'in q)errors.push(`問${i+1}: 未公開データに採点情報があります`);ids.add(q.id);positions.add(p)});for(const s of exam.sections){if(questions.filter(q=>q.section===s.id).length!==s.questionCount)errors.push(`${s.name}: 問題数不一致`)}return errors}
export function validateAnswerData(data,exam,questions){const errors=[],ids=new Set(questions.map(q=>q.id)),seen=new Set();if(data?.answerStatus!=='published')errors.push('公開済み正答データではありません');if(data?.schemaVersion!==exam.schemaVersion)errors.push('schemaVersion不一致');if(data?.examId!==exam.examId)errors.push('試験ID不一致');if(!Array.isArray(data?.answers))return[...errors,'正答一覧がありません'];for(const a of data.answers){if(!ids.has(a.questionId))errors.push(`未知の問題ID: ${a.questionId}`);if(seen.has(a.questionId))errors.push(`正答重複: ${a.questionId}`);if(!SCORING.includes(a.scoring))errors.push(`${a.questionId}: 採点方式不正`);const q=questions.find(x=>x.id===a.questionId);if(q&&a.correctAnswers?.some(v=>!Number.isInteger(v)||v<1||v>q.choiceCount))errors.push(`${a.questionId}: 正答範囲外`);if(['normal','multiple'].includes(a.scoring)&&!a.correctAnswers?.length)errors.push(`${a.questionId}: 正答なし`);if(a.scoring==='normal'&&a.correctAnswers?.length!==1)errors.push(`${a.questionId}: 通常正答は1つです`);seen.add(a.questionId)}if(data.answers.length!==questions.length)errors.push('正答数が問題数と一致しません');return errors}
export function mergeScoring(questions,data){const map=new Map(data.answers.map(a=>[a.questionId,a]));return questions.map(q=>({...q,...map.get(q.id),points:map.get(q.id)?.points??q.points}))}
export function scoreAnswer(value,q){if(q.scoring==='excluded')return{status:'excluded',earned:0,possible:0};const points=Number(q.points);if(q.scoring==='all_correct')return{status:'correct',earned:points,possible:points};if(value==null||value==='')return{status:'missing',earned:0,possible:points};if(value==='U')return{status:'unanswered',earned:0,possible:points};const correct=q.correctAnswers.includes(Number(value));return{status:correct?'correct':'incorrect',earned:correct?points:0,possible:points}}
export function scoreSubmission(answers,questions){let earned=0,possible=0;const categories={};const sections={};const details=questions.map(q=>{const r=scoreAnswer(answers[q.id]??'',q);earned+=r.earned;possible+=r.possible;for(const bucket of [categories[q.category]??={earned:0,possible:0},sections[q.section]??={earned:0,possible:0}]){bucket.earned+=r.earned;bucket.possible+=r.possible}return{...r,questionId:q.id,answer:answers[q.id]??''}});return{earned,possible,rate:possible?earned/possible:0,categories,sections,details}}
export function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;const source=text.replace(/^\uFEFF/,'');for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell=''}else cell+=c}if(quoted)throw Error('引用符が閉じていません');row.push(cell);if(row.some(v=>v!==''))rows.push(row);if(rows.length!==2)throw Error('1ファイルにつきヘッダー1行、学生データ1行が必要です');const headers=rows[0].map(v=>v.trim());if(new Set(headers).size!==headers.length)throw Error('ヘッダーが重複しています');return{headers,row:Object.fromEntries(headers.map((h,i)=>[h,rows[1][i]??'']))}}
export function validateSubmission(parsed,exam,questions){const errors=[],warnings=[],required=['exam_id','format_version',...questions.map(questionKey)],known=new Set([...required,'student_id','student_name','generated_at','data_version']);for(const h of required)if(!parsed.headers.includes(h))errors.push(`必須列不足: ${h}`);for(const h of parsed.headers)if(!known.has(h))warnings.push(`未知の列: ${h}`);const row=parsed.row;if(row.exam_id!==exam.examId)errors.push('試験ID不一致');if(row.format_version!==exam.formatVersion)errors.push('形式バージョン不一致');const answers={};for(const q of questions){const k=questionKey(q),v=(row[k]??'').trim();if(v!==''&&v!=='U'&&(!/^\d+$/.test(v)||Number(v)<1||Number(v)>q.choiceCount))errors.push(`${k}: 不正値「${v}」`);answers[q.id]=v}return{errors,warnings,answers}}
const escapeCsv=v=>{const s=String(v??'');return/[",\r\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s};
export function toCsv(rows){if(!rows.length)return'';const h=Object.keys(rows[0]);return'\uFEFF'+[h,...rows.map(r=>h.map(k=>r[k]??''))].map(r=>r.map(escapeCsv).join(',')).join('\r\n')}
